lsi: false
#markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:title
paginate: 10
exclude:
  - node_modules
  - package.json
  - README.md
title: skratchdot.com
url: https://www.skratchdot.com
devmode: false

source:      .
destination: ./_site
plugins:     ./_plugins

# Plugin Settings
category_dir: category
category_title_prefix: "Category: "
tag_dir: tag
tag_title_prefix: "Tag: "
